const simulatedOrders = [
  {
    seriesNumber: 'INV-E40035AA',
    issuedAt: '2025-06-30T14:36:22.002977',
    estate: 'Procesando',
    totalAmount: 479.8,
    shippingAddress: '123 Green Ave, Lima',
    customer: {
      id: 1,
      userCode: '74365182',
      firstName: 'Paquito',
      lastName: 'Paquito',
      email: 'Paquito@gmail.com',
      phone: '952154444',
      registrationDate: '2025-06-30',
      purchaseCount: 0,
      totalSpent: 0.0,
      address: 'Av.america',
    },
    details: [
      {
        id: 25,
        quantity: 1,
        unitPrice: 389.9,
        subtotal: 389.9,
        product: {
          id: 1,
          code: 38381,
          name: 'Silla Ergonómica ProOffice',
          description: 'Silla ergonómica con soporte lumbar para largas jornadas.',
          price: 389.9,
          discount: '10%',
        },
      },
      {
        id: 26,
        quantity: 1,
        unitPrice: 89.9,
        subtotal: 89.9,
        product: {
          id: 2,
          code: 45977,
          name: 'Lámpara LED Minimalista',
          description: 'Lámpara moderna con intensidad regulable.',
          price: 89.9,
          discount: '0%',
        },
      },
    ],
  },
  {
    seriesNumber: 'INV-E40035BB',
    issuedAt: '2025-06-30T12:20:15.002977',
    estate: 'Enviado',
    totalAmount: 299.5,
    shippingAddress: '456 Blue Street, Lima',
    customer: {
      id: 1,
      userCode: '74365182',
      firstName: 'Paquito',
      lastName: 'Paquito',
      email: 'Paquito@gmail.com',
      phone: '952154444',
      registrationDate: '2025-06-30',
      purchaseCount: 1,
      totalSpent: 479.8,
      address: 'Av.america',
    },
    details: [
      {
        id: 27,
        quantity: 2,
        unitPrice: 149.75,
        subtotal: 299.5,
        product: {
          id: 3,
          code: 12345,
          name: 'Mesa de Escritorio Moderna',
          description: 'Mesa de escritorio con diseño minimalista.',
          price: 149.75,
          discount: '5%',
        },
      },
    ],
  },
  {
    seriesNumber: 'INV-E40035CC',
    issuedAt: '2025-06-29T16:45:30.002977',
    estate: 'Entregado',
    totalAmount: 189.9,
    shippingAddress: '789 Red Avenue, Lima',
    customer: {
      id: 1,
      userCode: '74365182',
      firstName: 'Paquito',
      lastName: 'Paquito',
      email: 'Paquito@gmail.com',
      phone: '952154444',
      registrationDate: '2025-06-30',
      purchaseCount: 2,
      totalSpent: 779.3,
      address: 'Av.america',
    },
    details: [
      {
        id: 28,
        quantity: 1,
        unitPrice: 189.9,
        subtotal: 189.9,
        product: {
          id: 4,
          code: 67890,
          name: 'Organizador de Escritorio',
          description: 'Organizador multifuncional para escritorio.',
          price: 189.9,
          discount: '0%',
        },
      },
    ],
  },
  {
    seriesNumber: 'INV-E40035DD',
    issuedAt: '2025-06-28T09:15:45.002977',
    estate: 'Entregado',
    totalAmount: 599.99,
    shippingAddress: '321 Yellow Lane, Lima',
    customer: {
      id: 1,
      userCode: '74365182',
      firstName: 'Paquito',
      lastName: 'Paquito',
      email: 'Paquito@gmail.com',
      phone: '952154444',
      registrationDate: '2025-06-30',
      purchaseCount: 3,
      totalSpent: 1379.29,
      address: 'Av.america',
    },
    details: [
      {
        id: 29,
        quantity: 1,
        unitPrice: 599.99,
        subtotal: 599.99,
        product: {
          id: 5,
          code: 11111,
          name: 'Sillón Ejecutivo Premium',
          description: 'Sillón de cuero genuino para ejecutivos.',
          price: 599.99,
          discount: '15%',
        },
      },
    ],
  },
];

export default simulatedOrders;
